Repository Automattic/ad-code-manager, pull requests merged in 2022-03, with the labels that each got.

#120 Fix broken screenshot references in readme
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-2.jpg
  .wordpress-org/screenshot-3.jpg
  .wordpress-org/screenshot-4.jpg
  .wordpress-org/screenshot-5.jpg
  readme.md
Labels: Type: maintenance

#121 Docs: Cleanup readme
  readme.md
  readme.txt
Labels: Type: maintenance

#122 Docs: Rearrange sections, and further tidying
  readme.md
Labels: Type: docs

#126 Deploy: Add workflow for pushing to WPORG
  .github/workflows/deploy.yml
Labels: Type: maintenance

#127 Composer: Update dependencies
  composer.json
Labels: Type: maintenance

#128 Fix broken tests and workflows
  .github/workflows/cs-lint.yml
  .github/workflows/integrations.yml
  .gitignore
  composer.json
  phpunit.xml.dist
  tests/Integration/AdCodeManagerTest.php
  tests/Integration/TestCase.php
  tests/Integration/bootstrap.php
  tests/ad-code-manager-testcase.php
  tests/bootstrap.php
  tests/test-ad-code-manager.php
Labels: Type: maintenance

#131 Bump min PHP and WP versions
  composer.json
  readme.md
Labels: Type: maintenance

#132 Tests: Remove PHP 8.2 check
  .github/workflows/integrations.yml
Labels: Type: maintenance

#133 Tests: Remove PHP 8.2 check
  .github/workflows/integrations.yml
Labels: Type: maintenance

#135 Consolidate coding standards contributions
  ad-code-manager.php
  common/lib/acm-provider.php
  common/lib/acm-widget.php
  common/lib/acm-wp-list-table.php
  common/views/ad-code-manager.tpl.php
Labels: Type: maintenance

#111 Allow filtering the TTL for matching ad codes
  ad-code-manager.php
Labels: Type: enhancement

#137 Reorganise code
  acm.css
  acm.js
  ad-code-manager.php
  phpunit.xml.dist
  src/Providers/class-doubleclick-for-publishers-async.php
  src/Providers/class-doubleclick-for-publishers.php
  src/Providers/class-google-adsense-async.php
  src/Providers/class-google-adsense.php
  src/class-acm-provider.php
  src/class-acm-widget.php
  src/class-acm-wp-list-table.php
  src/class-ad-code-manager.php
  src/markdown.php
  views/ad-code-manager.tpl.php
Labels: Type: maintenance

#138 Add banner image from WPORG
  .wordpress-org/banner-772x250.png
Labels: Type: maintenance

#139 Change how main plugin class is initialized
  ad-code-manager.php
  src/class-ad-code-manager.php
  tests/Integration/bootstrap.php
Labels: Type: maintenance

#140 Check post type of the received post ID before deletion
  src/class-ad-code-manager.php
  tests/Integration/AdCodeManagerTest.php
Labels: Type: enhancement

#141 Fix: Bulk deletes not working
  src/class-ad-code-manager.php
Labels: Type: bug

#142 Create LICENSE
  LICENSE
Labels: Type: docs

#143 Create dependabot.yml
  .github/dependabot.yml
Labels: Type: maintenance

#144 Add .gitattributes file
  .gitattributes
Labels: Type: maintenance

#145 Fix dependabot config
  .github/dependabot.yml
Labels: Type: maintenance

#146 CS: Fix auto-fixable errors
  .phpcs.xml.dist
  ad-code-manager.php
  src/Providers/class-doubleclick-for-publishers-async.php
  src/Providers/class-doubleclick-for-publishers.php
  src/Providers/class-google-adsense-async.php
  src/Providers/class-google-adsense.php
  src/class-acm-provider.php
  src/class-acm-widget.php
  src/class-acm-wp-list-table.php
  src/class-ad-code-manager.php
  tests/Integration/AdCodeManagerTest.php
  tests/Integration/bootstrap.php
  views/ad-code-manager.tpl.php
Labels: Type: maintenance

#147 Fix untranslatable strings in PHP
  src/class-ad-code-manager.php
  views/ad-code-manager.tpl.php
Labels: Type: maintenance, Type: bug

#148 Move settings page
  src/class-acm-widget.php
  src/class-ad-code-manager.php
Labels: Type: enhancement

#149 Add link to settings page on plugin page
  ad-code-manager.php
  src/UI/class-plugin-actions.php
  tests/Integration/UI/PluginActionsTest.php
Labels: Type: enhancement

#150 Refactor action_acm_tag()
  src/class-ad-code-manager.php
Labels: Type: maintenance

#151 Refresh contextual help
  acm.css
  ad-code-manager.php
  src/UI/class-contextual-help.php
  src/class-ad-code-manager.php
  src/markdown.php
Labels: Type: maintenance, Type: docs

#152 Refresh screenshots
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.jpg
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.jpg
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.jpg
  .wordpress-org/screenshot-5.jpg
  readme.md
Labels: Type: docs

#153 Automate changelog from release notes
  .github/workflows/changelog.js
  .github/workflows/deploy.yml
  .gitignore
  package.json
  readme.md
Labels: Type: maintenance

#154 Add script to bump version numbers
  README.md
  ad-code-manager.php
  package.json
Labels: Type: maintenance

#156 Version 0.6.0 into develop
  README.md
  ad-code-manager.php
  package.json
Labels: Type: maintenance

#158 Deploy: Remove broken NPM caching
  .github/workflows/deploy.yml
Labels: Type: maintenance

#159 Deploy: Add manual trigger
  .github/workflows/deploy.yml
Labels: Type: maintenance

#160 Update deploy workflow for 0.6.0
  .github/workflows/deploy.yml
Labels: Type: bug
